CREATE TABLE worker(
ID int PRIMARY KEY,
NAME varchar(1000) NOT NULL CHECK(LENGTH(NAME) >=2),
BIRTHDAY DATE CHECK(EXTRACT(YEAR FROM Birthday) > 1900),
LEVEL varchar(50) CHECK(LEVEL IN('Trainee','Trainee','Middle','Senior')) NOT NULL,
SALARY int CHECK(SALARY>=100 AND SALARY<=100000),
);

CREATE TABLE client(
ID int PRIMARY KEY,
NAME varchar(1000) NOT NULL CHECK(LENGTH(NAME)>=2),
);

CREATE TABLE project(
ID int PRIMARY KEY,
CLIENT_ID int,
START_DATE DATE,
FINISH_DATA DATE
);

CREATE TABLE project_worker(
PROJECT_ID int,
WORKER_ID int,
PRIMARY KEY(PROJECT_ID,WORKER_ID),
FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);